sqlite:
  #sqlite路径（基于根目录）
  path: "ctlib/playerData.db"
mysql:
  #是否启用mysql？不启用会导致依赖于该插件的mysql部分无法运行
  enable: false
  #mysql驱动
  drive: "com.mysql.cj.jdbc.Driver"#旧版驱动: com.mysql.jdbc.Driver
  #服务器域名
  host: 127.0.0.1
  #服务器端口
  port: 3306
  #数据库名
  database: dbName
  #用户名
  username: example
  #密码
  password: password
  #服务器时区
  time: GMT
  #sql编码
  char: UTF-8
  #是否使用ssl
  useSSL: true